FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /cxl-mock-switch ./cxl-mock-switch

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /cxl-mock-switch /cxl-mock-switch
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/cxl-mock-switch"]
