apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cxl-system

resources:
  - rbac.yaml
  - deviceclass.yaml
  - resourceslice.yaml
  - mock-switch.yaml
  - controller.yaml
  - daemonset.yaml

images:
  - name: localhost:30500/cxl-dra-controller
    newName: ghcr.io/justin-oleary/cxl-dra-controller
    newTag: latest
  - name: localhost:30500/cxl-node-plugin
    newName: ghcr.io/justin-oleary/cxl-node-plugin
    newTag: latest
  - name: localhost:30500/cxl-mock-switch
    newName: ghcr.io/justin-oleary/cxl-mock-switch
    newTag: latest

commonLabels:
  app.kubernetes.io/name: cxl-dra-driver
  app.kubernetes.io/part-of: cxl-dra-driver
